export const images ={
    logo: require('../assets/images/forwardlogo.png'),
    google: require('../assets/images/google.png'),
    facebook: require('../assets/images/facebook.png'),
    apple: require('../assets/images/apple.png'),
    arrow: require('../assets/images/back_arrow.png'),
    downarrow: require('../assets/images/downarrow.png'),
    home:require('../assets/images/ic_home.png'),
    search: require('../assets/images/ic_srch.png'),
    post: require('../assets/images/ic_add.png'),
    notify: require('../assets/images/ic_notify.png'),
    profile: require('../assets/images/ic_user.png'),
    location: require('../assets/images/ic_loc.png'),
    homeicon: require('../assets/images/ic_home_icon.png'),
    userImage: require('../assets/images/userImage.jpeg'),
    postimage: require('../assets/images/postimage.webp'),
    dots: require('../assets/images/ic_dots.png'),
    direction: require('../assets/images/ic_direction.png'),
    key: require('../assets/images/ic_key.png'),
    logout: require('../assets/images/ic_logout.png'),
    userprofile: require('../assets/images/ic_usrr_1.png'),
    post1: require('../assets/images/post.jpeg'),
    editimage:require('../assets/images/editimage.jpeg'),
    edit:require('../assets/images/ic_edit.png'),
    cross:require('../assets/images/ic_crss.png'),

}