export default {
    LOGIN: 'LOGIN',
    SIGNUP:'SIGNUP',
    LOGOUT:'LOGOUT',
    CLEAR_REDUX_STATE: "CLEAR_REDUX_STATE",
    NO_INTERNET:"NO_INTERNET",
    INTRO:"INTRO",
    CHANGE_PASSWORD:"CHANGE_PASSWORD",
    EDIT_PROFILE:"EDIT_PROFILE",
};
  
   
