export default {
    LOGIN: 'LOGIN',
    SIGNUP:'SIGNUP',
    LOGOUT:'LOGOUT',
    CLEAR_REDUX_STATE: "CLEAR_REDUX_STATE",
    NO_INTERNET:"NO_INTERNET",
    INTRO:"INTRO",
    CHANGE_PASSWORD:"CHANGE_PASSWORD",
    EDIT_PROFILE:"EDIT_PROFILE",
    IMAGE_UPLOAD:'IMAGE_UPLOAD',
    POST_SEND: 'POST_SEND',
    POST: 'POST',
    LIKE_POST: 'LIKE_POST',
    COMMENT_POST: 'COMMENT_POST',
    COMMENT_GET: 'COMMENT_GET',
};
  
   
